#### Import Modules

In [1]:
import numpy as np
import tensorflow as tf

#### Generate 1D Array

In [80]:
arr_1d = np.array([0, 1, 2, 3, 4]).reshape(1,5,1).astype(np.float32)
#arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(1,5,2).astype(np.float32)
weight_1d = np.array([-1, 0, 1]).reshape(3,1,1).astype(np.float32)
#weight_1d = np.array([-1, 0, 1, -2, 0, 2]).reshape(3,2,1).astype(np.float32)

tf_arr_1d = tf.constant(arr_1d, name='arr_1d')
tf_weight_1d = tf.Variable(weight_1d, name='weight_1d')

#### Compute 1D Convolution

In [81]:
tf_conv1d_out = tf.nn.conv1d(value=tf_arr_1d, filters=weight_1d, stride=1, padding='VALID', 
                          data_format='NHWC', use_cudnn_on_gpu=True, name='conv1d' )

with tf.Session() as sess:
    conv1d_out = sess.run(tf_conv1d_out)
    print(conv1d_out, np.shape(conv1d_out))

(array([[[ 2.],
        [ 2.],
        [ 2.]]], dtype=float32), (1, 3, 1))


#### Generate 2D Array

In [99]:
arr_2d = np.random.randint(0, 10, size=(1, 6, 6, 1)).astype(np.float32)
weight_2d = np.random.randint(-2, 3, size=(3, 3, 1, 1)).astype(np.float32)

tf_arr_2d = tf.constant(arr_2d, name='arr_2d')
tf_weight_2d = tf.Variable(weight_2d, name='weight_2d')

#### Compute 2D Convolution

In [100]:
tf_conv2d_out = tf.nn.conv2d(input=tf_arr_2d, filter=weight_2d, strides=(1,1,1,1), padding='VALID', 
                          data_format='NHWC', use_cudnn_on_gpu=True, name='conv2d' )

with tf.Session() as sess:
    conv2d_out = sess.run(tf_conv2d_out)
    
print(arr_2d[0,:,:,0])
print(weight_2d[:,:,0,0])
print(conv2d_out[0,:,:,0])

[[ 4.  0.  8.  3.  7.  1.]
 [ 0.  3.  3.  7.  7.  9.]
 [ 4.  9.  5.  7.  8.  7.]
 [ 7.  1.  3.  2.  5.  8.]
 [ 7.  1.  4.  5.  0.  6.]
 [ 1.  8.  6.  6.  2.  1.]]
[[-1.  0.  1.]
 [ 0.  0. -2.]
 [-2.  2.  2.]]
[[ 18.  -5.   5.  -4.]
 [-13.  -2.  -4.  10.]
 [ -9.  10.  -5. -14.]
 [ 14.  -1.   6. -12.]]


#### Compute 2D Pooling

In [106]:
tf_avg_pool2d = tf.nn.avg_pool(value=tf_conv2d_out, ksize=(1,2,2,1), strides=(1,2,2,1), 
                               padding='VALID', data_format='NHWC', name='avg_pool2d')

tf_max_pool2d = tf.nn.max_pool(value=tf_conv2d_out, ksize=(1,3,3,1), strides=(1,1,1,1), 
                               padding='SAME', data_format='NHWC', name='max_pool2d')

with tf.Session() as sess:
    avg_pool2d_out = sess.run(tf_avg_pool2d)
    max_pool2d_out = sess.run(tf_max_pool2d)
    
print(avg_pool2d_out[0,:,:,0])
print(max_pool2d_out[0,:,:,0])

[[-0.5   1.75]
 [ 3.5  -6.25]]
[[ 18.  10.]
 [ 14.   6.]]
