# Python Basics
### This is markdown section
(#) is used for section headings. More (#) for subsections

(*) is used for bullet list

"Control + Enter" to run section

(Essential)
* Variable and Operations
* String and Print Formatting
* List and Dictionary
* Flow Control
* Functions
* Importing Libraries
* Numpy

(Optional)
* Lambda Functions
* Classes
* Writing and Reading File
* Exceptions

## Variable and Arithmetic Operations

In [27]:
# Integer Variable
intVal = 10
print intVal

# Addition
intVal = intVal + 10
print intVal

intVal += 10
print intVal

# Float Variable
floatVal = 5.0
print floatVal + 2.5

# Multiplication
floatVal *= 2
print floatVal

# Power
floatVal = floatVal ** 2
print floatVal

# Division
print 5/2
print 5.0/2

# Remainder
print 5%2

10
20
30
7.5
10.0
100.0
2
2.5
1
[0, 1, 2, 3, 4]


## Strings and Print Formatting

In [83]:
# String Variable
Str1 = "Hello,"
Str2 = "Python !!"
print Str1 + Str2

# Printing String
Str3 = "Welcome"
Str4 = "Deep Learning !"
print Str3 + " to " + Str4

print Str4.replace('Deep', 'Shallow')

# Print Formatting
print "I Love %s" % Str4

age = 20
height = 180.5
print "I am %d years old and %.2f cm tall." %(age, height)


Hello,Python !!
Welcome to Deep Learning !
Shallow Learning !
I Love Deep Learning !
I am 20 years old and 180.50 cm tall.


## List and Dictionary

In [56]:
# Number List
NumList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print NumList[5]
print NumList[-1]
print NumList[2:5]
NumList[-2] = 11
print NumList
del NumList[0]
print NumList
print len(NumList)

# New Line
print "\n"

# String List
EUNationList = ["Germany", "France", "England", "Spain"]
print EUNationList
EUNationList.append("Italy")
print EUNationList
EngInd = EUNationList.index("England")
print EngInd
EUNationList.pop(EngInd) #Brexit
print EUNationList
EUNationList.remove("Germany") #Collapse of EU
print EUNationList
print EUNationList + ["Greece", "Netherland"]

# New Line
print "\n"

# Dictionary
Person1 = {'Name' : 'John', 'Age' : 35, 'Job' : None}
print Person1['Age'] + 5
print Person1['Job']
Person1["Nationality"] = "Unknown"
print Person1
Person1["Age"] += 10
print Person1["Age"]
print Person1.keys()
print Person1.values()
print Person1.items()

# The list of items in the dictionary has type 'Tuple'. 
# Tuples are immutable ; we cannot add or delete element of tuples. 

6
10
[3, 4, 5]
[1, 2, 3, 4, 5, 6, 7, 8, 11, 10]
[2, 3, 4, 5, 6, 7, 8, 11, 10]
9


['Germany', 'France', 'England', 'Spain']
['Germany', 'France', 'England', 'Spain', 'Italy']
2
['Germany', 'France', 'Spain', 'Italy']
['France', 'Spain', 'Italy']
['France', 'Spain', 'Italy', 'Greece', 'Netherland']


40
None
{'Nationality': 'Unknown', 'Age': 35, 'Name': 'John', 'Job': None}
45
['Nationality', 'Age', 'Name', 'Job']
['Unknown', 45, 'John', None]
[('Nationality', 'Unknown'), ('Age', 45), ('Name', 'John'), ('Job', None)]


## Flow Control

In [93]:
# If Statement
Temp = 27
if Temp >= 33 :
    print "Very Hot!"
elif Temp >= 28 :
    print "Little Hot!"
elif Temp >=20 :
    print "Nice Weather!"
elif Temp >=15 :
    print "Warm!"
elif Temp >5 :
    print "Little Cold!"
else :
    print "Too Cold !"

# New Line
print "\n"    
    
# For Loop
for ind in range(10):
    print 2**(ind+1)

# List Comprehension
PowerList = [2 ** (x+1) for x in range(10)]
print PowerList
    
# New Line
print "\n"    
    
EUNationList = ["Germany", "France", "England", "Spain"]
CapDict = {"Germany" : "Berlin", "France" : "Paris", "England" : "London", "Spain" : "Barcelona"}

for nation in EUNationList :
    print CapDict[nation]

# New Line
print "\n"   
    
# While Loop
Age = 15
while Age < 20:
    print "Your are %d years old. Too young to drink!" %Age
    Age += 1
else:
    print "You finally became %d years old. Drink Responsibly !" %Age

    

Nice Weather!


2
4
8
16
32
64
128
256
512
1024
[2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]


Berlin
Paris
London
Barcelona


Your are 15 years old. Too young to drink!
Your are 16 years old. Too young to drink!
Your are 17 years old. Too young to drink!
Your are 18 years old. Too young to drink!
Your are 19 years old. Too young to drink!
You finally became 20 years old. Drink Responsibly !


## Functions

In [68]:
def print_info(Name, Age=10) :
    print "Name is %s" %Name
    print "Age is %d \n" %Age
    
print_info("James", 50)
print_info("Jessy")

def sum_int_between(start_num, end_num) :
    NumList = range(start_num, end_num+1)
    return sum(NumList)

print sum_int_between(1, 10)


Name is James
Age is 50 

Name is Jessy
Age is 10 

55


## Importing Libraries

In [80]:
# How can we see all the files in the current directory?
import os
print os.listdir('./')

import math
MathModules = dir(math)
print MathModules
print math.sin(math.pi)

from math import sin, cos, pi
print sin(pi), cos(2*pi)
# There are so many useful libraries for python. Numpy is one of most widely used library for numeric computation. 

['.ipynb_checkpoints', 'Python Basics.ipynb', 'TensorFlow Basics.ipynb']
['__doc__', '__name__', '__package__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'hypot', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'modf', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'trunc']
1.22464679915e-16
-2.44929359829e-16 1.0


## Numpy - Basic Arrays and Indexing

In [87]:
import numpy as np

#Basic Array 
a = np.array([1, 2, 3])  
print type(a)            
print a.shape            
print a[0], a[1], a[2]   
a[0] = 5                 
print a                  

b = np.array([[1,2,3],[4,5,6]])   
print b.shape                     
print b[0, 0], b[0, 1], b[1, 0]   

a = np.zeros((2,2))  
print a              
                         
b = np.ones((1,2))   
print b              

d = np.eye(2)        
print d              
                     
e = np.random.random((2,2))
print e                   
                           
    
print "\n----------------------------------------------------------------------------\n"
    
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2, 1:3]

print a[0, 1]   
b[0, 0] = 77   
print a[0, 1]   

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    
row_r2 = a[1:2, :] 
print row_r1, row_r1.shape  
print row_r2, row_r2.shape 

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print col_r1, col_r1.shape  
print col_r2, col_r2.shape                             


<type 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.30451157  0.9074601 ]
 [ 0.31602474  0.26850262]]

----------------------------------------------------------------------------

2
77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


## Numpy - Array Math

In [88]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print x + y
print np.add(x, y)

print x - y
print np.subtract(x, y)

print x * y
print np.multiply(x, y)

print x / y
print np.divide(x, y)

print np.sqrt(x)

print "\n----------------------------------------------------------------------------\n"

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print v.dot(w)
print np.dot(v, w)

print x.dot(v)
print np.dot(x, v)


print x.dot(y)
print np.dot(x, y)

print "\n----------------------------------------------------------------------------\n"

x = np.array([[1,2],[3,4]])

print np.sum(x)  # Compute sum of all elements; prints "10"
print np.sum(x, axis=0)  # Compute sum of each column; prints "[4 6]"
print np.sum(x, axis=1)  # Compute sum of each row; prints "[3 7]"



[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]

----------------------------------------------------------------------------

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]

----------------------------------------------------------------------------

10
[4 6]
[3 7]
